apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-src
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalAppPort }}
      protocol: TCP
      name: {{ .Release.Name }}-app
    - port: {{ .Values.service.internalServicePort }}
      targetPort: {{ .Values.service.internalServicePort }}
      protocol: TCP
      name: {{ .Release.Name }}-service
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
